CREATE TABLE `actionQueueItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`symbol` varchar(24) NOT NULL,
	`name` varchar(255) NOT NULL,
	`status` enum('WAITING_MATERIAL','REANALYZING','PENDING_ACTION','APPROVED','SNOOZED','SKIPPED','COMPLETED','FAILED') NOT NULL DEFAULT 'PENDING_ACTION',
	`triggerType` enum('INITIAL_REVIEW','EARNINGS','IMPORTANT_NEWS','MANUAL_ANALYSIS','SIGNAL_CHANGE') NOT NULL,
	`triggerKey` varchar(191) NOT NULL,
	`triggerSummary` text,
	`sourceNewsId` int,
	`sourceSignalId` int,
	`previousSignalId` int,
	`previousAction` enum('ADD','HOLD','WATCH','REDUCE','EXIT'),
	`action` enum('ADD','HOLD','WATCH','REDUCE','EXIT'),
	`direction` enum('BUY','NONE','REVIEW','SELL','EXIT'),
	`currency` varchar(8) NOT NULL,
	`rationale` text,
	`evidence` json,
	`currentQuantity` decimal(20,4),
	`currentPrice` decimal(20,4),
	`currentValueBase` decimal(20,2),
	`currentWeightPct` decimal(10,4),
	`recommendedShares` decimal(20,4),
	`recommendedAmountLocal` decimal(20,2),
	`recommendedAmountBase` decimal(20,2),
	`afterQuantity` decimal(20,4),
	`afterWeightPct` decimal(10,4),
	`priority` int NOT NULL DEFAULT 0,
	`deadline` timestamp,
	`snoozedUntil` timestamp,
	`decisionNote` text,
	`approvedAt` timestamp,
	`skippedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `actionQueueItems_id` PRIMARY KEY(`id`),
	CONSTRAINT `action_queue_user_trigger_unique` UNIQUE(`userId`,`triggerKey`)
);
--> statement-breakpoint
CREATE INDEX `action_queue_user_status_deadline_idx` ON `actionQueueItems` (`userId`,`status`,`deadline`);--> statement-breakpoint
CREATE INDEX `action_queue_user_symbol_updated_idx` ON `actionQueueItems` (`userId`,`symbol`,`updatedAt`);